# Generated by Django 4.2.7 on 2023-12-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_product_price_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='image',
        ),
    ]
