# Generated by Django 4.2.7 on 2023-12-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_remove_supplier_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='launch_date',
        ),
    ]
